<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * SimHub.
 *
 * @package    local_simhub
 * @copyright  2026 Écoles nationales vétérinaires de France (ENVF)
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['pluginname'] = 'SimHub';
$string['nav_accueil'] = 'SimHub home';
$string['nav_seance'] = 'Current session';
$string['nav_qrcode'] = 'Workshop QR code';
$string['nav_plan'] = 'Marker on room plan';
$string['nav_ressources'] = 'Learning resources';
$string['nav_retour'] = 'Back';
$string['simhub:studenthome'] = 'My workshops';

$string['setting_envcode'] = 'Institution code';
$string['setting_envcode_desc'] = 'Short code of the school (e.g. ENVA, ENVT, ONIRIS, VETAGROSUP). Each school has its own Moodle, so it is only used for traceability: it is stored on created or imported workshops, pathways and ASV acts, and included in exports.';
$string['setting_seancecodeduration'] = 'Session code validity';
$string['setting_seancecodeduration_desc'] = 'How long a temporary session code (anti-fake-scan control) stays valid.';
$string['setting_asvtokenexpiry'] = 'ASV external validation link validity';
$string['setting_asvtokenexpiry_desc'] = 'How long the link sent to an external validator (vet, placement supervisor...) remains active.';
$string['setting_controlepresenceactif'] = 'Enable anti-fake-scan control';
$string['setting_controlepresenceactif_desc'] = 'If disabled, no presence check is required when scanning a workshop QR code.';
$string['setting_etablissementnom'] = 'Institution name';
$string['setting_etablissementnom_desc'] = 'Full name shown in the header of PDF documents (certificates, ASV logbook, workshop sheets), e.g. "École Nationale Vétérinaire d\'Alfort".';
$string['setting_logo'] = 'Institution logo';
$string['setting_logo_desc'] = 'Image shown in the header of PDF documents generated by SimHub (pathway completion certificates, ASV logbook, workshop sheets). Accepted formats: PNG, JPG, SVG.';

$string['statut_actif'] = 'Active';
$string['statut_non_utilise'] = 'Not in use';
$string['statut_indisponible'] = 'Unavailable';
$string['statut_archive'] = 'Archived';

$string['niveau_reussi'] = 'Achieved';
$string['niveau_a_consolider'] = 'To consolidate';
$string['niveau_a_reprendre'] = 'To redo';

$string['simhub:view'] = 'View SimHub';
$string['simhub:startsession'] = 'Start / end a workshop';
$string['simhub:submitautoeval'] = 'Submit a guided self-assessment';
$string['simhub:viewprogression'] = 'View student progression';
$string['simhub:validatesession'] = 'Validate a workshop completion';
$string['simhub:exportsuivi'] = 'Export tracking data';
$string['simhub:manageparcours'] = 'Manage learning pathways';
$string['simhub:managerattachement'] = 'Manage pedagogical links';
$string['simhub:manageateliers'] = 'Manage workshop records';
$string['simhub:manageressources'] = 'Manage learning resources';
$string['simhub:managestatuts'] = 'Manage statuses and unavailability';
$string['simhub:manageqrcodes'] = 'Manage QR codes';
$string['simhub:importexport'] = 'Import / export data';
$string['simhub:manageasv'] = 'Administer the ASV module';
$string['simhub:validateasvsimulation'] = 'Validate an ASV act in simulation';
$string['simhub:configure'] = 'Configure SimHub';

$string['privacy:metadata:local_simhub_session'] = 'History of simulation workshops completed by the user.';
$string['privacy:metadata:local_simhub_session:userid'] = 'The id of the user who completed the workshop.';
$string['privacy:metadata:local_simhub_session:atelierid'] = 'The workshop involved.';
$string['privacy:metadata:local_simhub_session:timestart'] = 'The date the session started.';
$string['privacy:metadata:local_simhub_session:timeend'] = 'The date the session ended.';
$string['privacy:metadata:local_simhub_session:statut'] = 'The session status (started, completed, certified, unfinished).';

$string['privacy:metadata:local_simhub_ae_reponse'] = 'User answers to self-assessment criteria.';
$string['privacy:metadata:local_simhub_ae_reponse:sessionid'] = 'The session involved.';
$string['privacy:metadata:local_simhub_ae_reponse:critereid'] = 'The criterion assessed.';
$string['privacy:metadata:local_simhub_ae_reponse:niveau'] = 'The level reached (achieved, to consolidate, to redo).';

$string['privacy:metadata:local_simhub_ae_bilan'] = 'End-of-workshop self-assessment summaries written by the user.';
$string['privacy:metadata:local_simhub_ae_bilan:sessionid'] = 'The session involved.';
$string['privacy:metadata:local_simhub_ae_bilan:pointmaitrise'] = 'The best-mastered point, as written by the user.';
$string['privacy:metadata:local_simhub_ae_bilan:pointaretravailler'] = 'The point to work on, as written by the user.';
$string['privacy:metadata:local_simhub_ae_bilan:pointattention'] = 'The point of attention for next time, as written by the user.';

$string['privacy:metadata:local_simhub_val_encadrant'] = 'Workshop validations performed by a supervisor.';
$string['privacy:metadata:local_simhub_val_encadrant:sessionid'] = 'The session validated.';
$string['privacy:metadata:local_simhub_val_encadrant:validateuruserid'] = 'The supervisor who performed the validation.';
$string['privacy:metadata:local_simhub_val_encadrant:statut'] = 'The validation outcome (validated, rejected).';
$string['privacy:metadata:local_simhub_val_encadrant:commentaire'] = 'The supervisor\'s free-text comment.';

$string['privacy:metadata:local_simhub_asv_valsim'] = 'ASV simulation validations.';
$string['privacy:metadata:local_simhub_asv_valsim:userid'] = 'The student concerned by the validation.';
$string['privacy:metadata:local_simhub_asv_valsim:acteid'] = 'The ASV act concerned.';
$string['privacy:metadata:local_simhub_asv_valsim:validateuruserid'] = 'The supervisor who validated the act.';
$string['privacy:metadata:local_simhub_asv_valsim:statut'] = 'The validation outcome.';

$string['privacy:metadata:local_simhub_asv_valanimal'] = 'ASV live-animal validation data, including external validator identity and signature.';
$string['privacy:metadata:local_simhub_asv_valanimal:userid'] = 'The student concerned by the validation.';
$string['privacy:metadata:local_simhub_asv_valanimal:acteid'] = 'The ASV act concerned.';
$string['privacy:metadata:local_simhub_asv_valanimal:nomvalidateur'] = 'The validator\'s last name (possibly external to Moodle).';
$string['privacy:metadata:local_simhub_asv_valanimal:prenomvalidateur'] = 'The validator\'s first name.';
$string['privacy:metadata:local_simhub_asv_valanimal:signature'] = 'The validator\'s signature trace.';

$string['event_atelier_created'] = 'Workshop created';
$string['event_session_started'] = 'Workshop session started';
$string['event_session_completed'] = 'Workshop session completed';
$string['event_asv_valide_simulation'] = 'ASV act validated in simulation';
$string['event_asv_valide_animal'] = 'ASV act validated on a live animal';

$string['manage_ateliers'] = 'Workshop management';
$string['rattachements'] = 'Course links';
$string['ae_modele'] = 'Self-assessment grid';
$string['ae_champ_titre'] = 'Title';
$string['ae_champ_actif'] = 'Grid active';
$string['ae_champ_risques'] = 'Rubric dedicated to errors/risks';
$string['ae_champ_critere'] = 'New criterion';
$string['ae_gerer_rubriques'] = 'Manage rubrics and criteria';
$string['ae_ajouter_rubrique'] = 'Add a rubric';
$string['ae_ajouter_critere'] = 'Add';
$string['ae_badge_risques'] = 'Errors/risks';

$string['qr_lien_intro'] = 'This QR code opens the workshop sheet and starts a session on scan (§7). Print it and stick it on the workshop.';
$string['qr_regenerer'] = 'Regenerate the link (invalidates the previously printed QR code)';
$string['qr_imprimer'] = 'Print';
$string['qr_telecharger'] = 'Download (SVG)';
$string['atelier_nouveau'] = 'New workshop';
$string['atelier_modifier'] = 'Edit workshop';
$string['atelier_enregistre'] = 'Workshop saved.';
$string['atelier_supprime'] = 'Workshop deleted.';
$string['parcours_nouveau'] = 'New pathway';
$string['ressource_nouvelle'] = 'New resource';
$string['autoeval_enregistree'] = 'Self-assessment saved.';
$string['session_terminee'] = 'Workshop completed.';
$string['session_demarree'] = 'Workshop started.';
$string['asv_validation_enregistree'] = 'ASV validation recorded.';
$string['champ_numero'] = 'Number (invariant)';
$string['champ_nomcourt'] = 'Short name';
$string['champ_nomlong'] = 'Long name';
$string['champ_descriptioncourte'] = 'Short description';
$string['champ_discipline'] = 'Discipline';
$string['champ_espece'] = 'Species';
$string['champ_niveaudifficulte'] = 'Difficulty level';
$string['champ_dureeindicative'] = 'Estimated duration (minutes)';
$string['champ_statut'] = 'Status';
$string['champ_envcode'] = 'Institution';
$string['champ_salle'] = 'Room';
$string['champ_zone'] = 'Zone';
$string['champ_codeposte'] = 'Workstation code / number';
$string['champ_indicationtextuelle'] = 'Text hint';
$string['champ_commentaireadmin'] = 'Comment (internal)';
$string['champ_commentaire_indispo'] = 'Comment about the unavailability';
$string['champ_echeance_indispo'] = 'Estimated resolution date';
$string['champ_pointmaitrise'] = 'Best-mastered point';
$string['champ_pointaretravailler'] = 'Point to work on';
$string['champ_pointattention'] = 'Point of attention for next time';

$string['filtre_uc'] = 'Course';
$string['filtre_parcours'] = 'Pathway';
$string['filtre_annee'] = 'Study year';
$string['filtre_discipline'] = 'Discipline';
$string['filtre_espece'] = 'Species';
$string['filtre_niveau'] = 'Difficulty level';
$string['filtre_duree'] = 'Duration';
$string['filtre_statutperso'] = 'Personal status';
$string['filtre_motcle'] = 'Keyword';
$string['filtre_appliquer'] = 'Filter';
$string['filtre_reinitialiser'] = 'Reset';
$string['statutperso_pascommence'] = 'Not started';
$string['statutperso_commence'] = 'Started';
$string['statutperso_realise'] = 'Completed';
$string['statutperso_valide'] = 'Validated';
$string['statutperso_areprendre'] = 'To redo';
$string['aucun_atelier'] = 'No workshop matches these criteria.';
$string['bouton_localisation'] = 'Show location';
$string['bouton_ressources'] = 'View resources';
$string['bouton_commencer'] = 'Start';
$string['bouton_terminer'] = 'Finish workshop and self-assess';
$string['section_mesuc'] = 'To do for my courses';
$string['section_parcours'] = 'My ongoing pathways';
$string['section_asv'] = 'ASV pathway';
$string['section_commences'] = 'Workshops already started';
$string['section_areprendre'] = 'Workshops to redo';
$string['section_tous'] = 'All available workshops';
$string['section_recommandes'] = 'Recommended for my group';
$string['champ_cohorte'] = 'Group (Moodle cohort)';

$string['asv_gerer_actes'] = 'Manage act catalogue';
$string['asv_acte_nouveau'] = 'New act';
$string['asv_acte_inactif'] = 'Inactive';
$string['asv_champ_code'] = 'Code';
$string['asv_champ_niveau'] = 'Level';
$string['asv_champ_ucid'] = 'Course (UC id)';
$string['asv_parcours'] = 'ASV pathway';
$string['asv_livret'] = 'ASV competency logbook';
$string['asv_ateliers_lies'] = 'Workshops where this act is practiced';
$string['asv_lier_atelier'] = 'Link this workshop';
$string['asv_aucun_acte_lie'] = 'No act linked to this workshop: showing the full catalogue.';
$string['asv_valider_depuis_atelier'] = 'Validate an ASV act for this workshop';
$string['asv_attestations_groupees'] = 'Certification attestations (bulk generation)';
$string['asv_aucun_eligible'] = 'No student has fully validated this level yet.';
$string['asv_nb_eligibles'] = '{$a} student(s) have validated this level and can receive their attestation.';
$string['asv_telecharger_tout'] = 'Download all attestations (ZIP)';
$string['asv_telecharger'] = 'Download';
$string['filtrer'] = 'Filter';
$string['asv_valider_simulation'] = 'Validate in simulation';
$string['asv_demander_validation_animal'] = 'Request a live-animal validation';
$string['asv_formulaire_validateur_titre'] = 'Live-animal act validation';
$string['asv_champ_nom'] = 'Last name';
$string['asv_champ_prenom'] = 'First name';
$string['asv_champ_certification'] = 'I certify that I am a veterinarian or an authorised supervisor for this act.';
$string['asv_champ_signature'] = 'Signature';
$string['asv_valide_avec_succes'] = 'Validation recorded. Thank you.';
$string['asv_lien_invalide'] = 'This validation link is invalid or has expired.';
// Anti-fake-scan control (§7.3).
$string['seancecode_intro'] = 'A presence check is required for this workshop: enter the session code displayed in the room by the supervisor.';
$string['seancecode_champ'] = 'Session code';
$string['seancecode_valider'] = 'Validate code';
$string['seancecode_pasdecode'] = 'I have no code, start anyway';
$string['seancecode_invalide'] = 'This code is invalid or has expired. You can start without a code: your completion will then be submitted for validation by a supervisor.';
$string['seancecode_sansvalidation'] = 'Session started without a session code. Your completion will need to be validated by a supervisor.';
$string['seancecode_generer'] = 'Generate a session code';
$string['seancecode_champ_salle'] = 'Room';
$string['seancecode_genere'] = 'Generated code';
$string['seancecode_validite'] = 'Valid until {$a}';
$string['sessions_a_valider'] = 'Sessions to validate';

$string['dashboard_parcours'] = 'Pathway dashboard';
$string['dashboard_salle'] = 'Room dashboard';
$string['dashboard_sansressource'] = 'No resource';
$string['dashboard_sansuc'] = 'No course link';
$string['dashboard_peuutilise'] = 'Rarely used';

$string['badge_aucun'] = 'None';
$string['champ_badge'] = 'Badge awarded on completion (optional)';
$string['setting_badgeasva1'] = 'ASV badge — level A1';
$string['setting_badgeasva1_desc'] = 'Site badge automatically awarded to the student when they generate the A1 certification attestation (§9.4).';
$string['setting_badgeasva2'] = 'ASV badge — level A2';
$string['setting_badgeasva2_desc'] = 'Site badge automatically awarded to the student when they generate the A2 certification attestation (§9.4).';
$string['setting_badgeasva3'] = 'ASV badge — level A3';
$string['setting_badgeasva3_desc'] = 'Site badge automatically awarded to the student when they generate the A3 certification attestation (§9.4, "certification globale de fin de A3").';
$string['sessions_aucune_a_valider'] = 'No session awaiting validation.';
$string['session_valider'] = 'Validate';
$string['session_refuser'] = 'Reject';

$string['asv_niveau_a1'] = 'A1';
$string['asv_niveau_a2'] = 'A2';
$string['asv_niveau_a3'] = 'A3';

$string['import_ateliers'] = 'Import workshops';
$string['import_description'] = 'Imports data from a CSV, Excel (XLSX) or LibreOffice (ODS) file; for a workbook, only the first sheet is read. Columns may be in any order and under various headings (accents and case ignored): school spreadsheets do not need to be harmonised first. Column details for each type are in the help of the "Import type" field.';
$string['import_fichier'] = 'CSV file';

$string['export_csv'] = 'Export (CSV)';

// Navigation par domaines, onglets et sélecteurs.
$string['onglet_fiche'] = 'Record';
$string['onglet_vue_etudiant'] = 'Student view';
$string['onglet_pdf'] = 'PDF sheet';
$string['onglet_composition'] = 'Composition';
$string['onglet_suivi'] = 'Tracking';
$string['onglet_export_csv'] = 'CSV export';
$string['nav_gerer'] = 'Manage';
$string['nav_groupe_accueil'] = 'My space';
$string['nav_groupe_ateliers'] = 'Workshops';
$string['nav_groupe_parcours'] = 'Pathways';
$string['nav_groupe_seances'] = 'Sessions';
$string['nav_groupe_asv'] = 'ASV';
$string['type'] = 'Type';
$string['nb_ateliers'] = 'Workshops';
$string['parcours_type_recommande'] = 'Recommended';
$string['parcours_type_obligatoire'] = 'Mandatory';
$string['parcours_type_lie_uc'] = 'Linked to a course unit';
$string['parcours_type_lie_annee'] = 'Linked to a year';
$string['parcours_type_certifiant'] = 'Certifying';
$string['parcours_type_asv'] = 'ASV';
$string['aucune_uc'] = '— No course unit —';
$string['choisir_etudiant'] = '— Choose a student —';
$string['atelier_aucun_choix'] = '— No workshop —';
$string['champ_uc_optionnel'] = 'Moodle course unit (optional)';
$string['rattachement_ajouter'] = 'Add a link';
$string['optionnel'] = '(optional)';
$string['champ_cohorte_recommandation'] = 'Cohort (optional — to recommend directly to its members)';
$string['etudiant'] = 'Student';
$string['asv_acte'] = 'Procedure';
$string['asv_atelier_associe'] = 'Related simulation workshop (optional)';
$string['asv_certification_a3'] = 'End of A3 global certification';
$string['asv_signature_effacer'] = 'Clear signature';
$string['asv_valider_acte'] = 'Validate this procedure';
$string['telecharger_fiche_pdf'] = 'Download the sheet (PDF)';
$string['gerer_atelier'] = 'Manage this workshop';
$string['asv_code_existe'] = 'The procedure code "{$a}" already exists for this institution.';
$string['numero_existe'] = 'This workshop number is already used in this institution.';

// Rôles système (§11).
$string['nav_roles'] = 'SimHub roles';
$string['nav_groupe_roles'] = 'Roles';
$string['role_simhubencadrant'] = 'SimHub trainer';
$string['role_simhubencadrant_desc'] = 'Cross-cutting trainer assigned in the SimHub category: tracking of all pathways, session and simulation ASV validation for every student. A course unit teacher does not need it (§11).';
$string['role_simhubresponsableuc'] = 'SimHub course unit lead';
$string['role_simhubresponsableuc_desc'] = 'Cross-cutting view of pathways and links of every course unit. A course unit lead manages their own from the SimHub activity of their course, without this role (§11).';
$string['role_simhubgestionnairesalle'] = 'SimHub room manager';
$string['role_simhubgestionnairesalle_desc'] = 'Room manager: workshop records, resources, statuses, QR codes, import/export (§11).';
$string['role_simhubadminfonctionnel'] = 'SimHub functional administrator';
$string['role_simhubadminfonctionnel_desc'] = 'All SimHub rights, including the ASV framework and configuration, and assignment of the other SimHub roles in the SimHub category (§11).';

// Textes auparavant codés en dur dans les pages.
$string['ae_autobilan'] = 'Self-review';
$string['asv_acte_libelle'] = 'Procedure: {$a}';
$string['asv_transmettre_lien'] = 'Enter the email address of the veterinarian, placement supervisor or authorised trainer who supervised the procedure on a live animal: the validation link is sent directly to them.';
$string['asv_exporter_livret'] = 'Export the logbook (PDF)';
$string['asv_col_simulation'] = 'Simulation';
$string['asv_col_animal'] = 'Live animal';
$string['asv_col_valides_simulation'] = 'Validated in simulation';
$string['asv_col_valides_animal'] = 'Validated on live animal';
$string['asv_col_validation_simulation'] = 'Simulation validation';
$string['asv_col_validation_animal'] = 'Live animal validation';
$string['asv_aucun_acte_niveau'] = 'No {$a} procedure in this institution\'s framework.';
$string['asv_certification_niveau'] = 'Certification {$a}';
$string['asv_certification_incomplete'] = 'The {$a->niveau} certification for {$a->nom} cannot be issued yet: {$a->nb} procedure(s) remain to be validated.';
$string['attestation_incomplete'] = 'The certificate cannot be issued yet: {$a->nom} has completed {$a->pct}% of the pathway "{$a->parcours}" ({$a->realises}/{$a->total} workshops done).';
$string['attestation_titre'] = 'Certificate of completion';
$string['pdf_certifie_que'] = '{$a} certifies that';
$string['attestation_parcours_realise'] = 'has completed all the workshops of the pathway <b>{$a}</b>.';
$string['atelier'] = 'Workshop';
$string['pdf_delivree_le'] = 'Issued on {$a}';
$string['asv_attestation_titre'] = 'Certificate of certification';
$string['asv_attestation_soustitre'] = 'Delegable veterinary procedures (ASV) — level {$a}';
$string['asv_attestation_texte'] = 'has validated, in simulation then on a live animal, all the delegable veterinary procedures of level {$a} listed below:';
$string['asv_manque_simulation'] = 'simulation missing';
$string['asv_manque_animal'] = 'live animal missing';
$string['avancement'] = 'Progress';
$string['suivi_valide'] = 'Validated';
$string['suivi_realise'] = 'Done';
$string['suivi_commence'] = 'Started';
$string['attestation_pdf'] = 'Certificate (PDF)';
$string['rattachements_existants'] = 'Existing links';
$string['retirer'] = 'Remove';
$string['niveau_attendu_optionnel'] = 'Expected level (optional)';
$string['plan_absent'] = 'No room plan image has been uploaded for this workshop yet.';
$string['plan_consigne'] = 'Click on the plan where the workshop is located.';
$string['plan_positionner'] = 'Place the marker on the plan';
$string['dash_etudiants'] = 'Students';
$string['dash_avancement_moyen'] = 'Average progress';
$string['dash_pas_commence'] = 'Not started';
$string['dash_commence'] = 'Started';
$string['dash_termine'] = 'Completed';
$string['dash_a_reprendre'] = 'To redo';
$string['dash_echeance'] = 'Deadline near/overdue';
$string['detail'] = 'Details';
$string['parcours_ateliers_titre'] = 'Pathway workshops';
$string['parcours_ajouter_atelier'] = 'Add a workshop';
$string['ordre'] = 'Order';
$string['echeance_optionnel'] = 'Deadline (optional)';
$string['import_aucun_fichier'] = 'No file received.';
$string['import_ordre'] = 'Import workshop records first: the other imports find each workshop by its number.';
$string['import_type'] = 'Import type';
$string['import_type_rattachements'] = 'Links (course unit / year / cohort)';
$string['import_type_parcours'] = 'Pathway composition';
$string['import_separateur'] = 'Separator';
$string['import_sep_pointvirgule'] = 'Semicolon (;) — French Excel';
$string['import_sep_virgule'] = 'Comma (,)';
$string['import_fichier_vide'] = 'Empty file.';
$string['import_colonnes_manquantes'] = 'Required columns not found: at least a workshop number and name are needed.';
$string['import_ligne_numero_nom'] = 'Line {$a} skipped: number or name missing.';
$string['import_ligne_numero'] = 'Line {$a} skipped: workshop number missing.';
$string['import_ligne_parcours'] = 'Line {$a} skipped: pathway or workshop number missing.';
$string['import_colonne_manquante'] = 'Required column not found: {$a}.';
$string['niveau_facile'] = 'Easy';
$string['niveau_intermediaire'] = 'Intermediate';
$string['niveau_avance'] = 'Advanced';
$string['champ_planimage'] = 'Room plan image';
$string['ressource_type_fiche_methode'] = 'Method sheet';
$string['ressource_type_pdf_etudiant'] = 'Student PDF';
$string['ressource_type_video'] = 'Video';
$string['ressource_type_consignes'] = 'Instructions';
$string['ressource_type_criteres_reussite'] = 'Success criteria';
$string['ressource_type_erreurs_frequentes'] = 'Common mistakes';
$string['ressource_type_liens_utiles'] = 'Useful links';
$string['ressource_type_complementaire'] = 'Additional';
$string['ressource_type_source_editable'] = 'Editable source (never visible to students)';
$string['champ_visibilite'] = 'Visibility';
$string['visibilite_interne'] = 'Internal (managers only)';
$string['champ_url_ressource'] = 'External link (optional if a file is provided)';
$string['champ_fichier_ressource'] = 'File (optional if a link is provided)';
$string['champ_ordre_affichage'] = 'Display order';
$string['ressource_lien_ou_fichier'] = 'Provide a link or a file.';
$string['import_ligne_erreur'] = 'Line {$a->ligne}: {$a->erreur}';
$string['import_ligne_atelier_introuvable'] = 'Line {$a->ligne} skipped: workshop {$a->numero} ({$a->envcode}) not found — import it first.';

// Module ASV : refus, annulation, demandes en attente, certification globale.
$string['asv_non_valide_le'] = 'Not validated on {$a}';
$string['asv_en_attente_jusquau'] = 'Request pending (link valid until {$a})';
$string['asv_annuler_simulation'] = 'Cancel the simulation validation';
$string['asv_annuler_animal'] = 'Cancel the live animal validation';
$string['asv_voir_lien'] = 'Follow the validation request';
$string['asv_telecharger_attestation'] = 'Download the certificate';
$string['asv_actes_restants'] = '{$a} procedure(s) remaining';
$string['asv_motif_obligatoire'] = 'A reason for the cancellation is required.';
$string['asv_annule_par'] = 'Cancelled by {$a->nom} on {$a->date}: {$a->motif}';
$string['asv_validation_annulee'] = 'Validation cancelled. It remains recorded but no longer counts towards the logbook or certification.';
$string['asv_confirmer_annulation'] = 'Cancel the validation of the procedure "{$a->acte}" for {$a->etudiant}?';
$string['asv_motif'] = 'Reason (kept in the history)';
$string['asv_confirmer'] = 'Confirm cancellation';
$string['asv_resultat'] = 'Result';
$string['asv_resultat_valide'] = 'Validated';
$string['asv_resultat_non_valide'] = 'Not validated (to redo)';
$string['asv_commentaire'] = 'Remark (optional)';
$string['asv_enregistrer_decision'] = 'Save the decision';
$string['asv_decision_enregistree'] = 'Decision saved.';
$string['asv_simulation_requise'] = 'This procedure must first be validated in simulation before a live animal validation can be requested.';
$string['asv_validation_incomplete'] = 'Validation not saved: enter your last and first name, tick the certification and sign in the box.';
$string['asv_signature_requise'] = 'Please sign in the box before validating.';
$string['asv_tous_etudiants'] = 'All students with an ASV validation';
$string['asv_col_en_attente'] = 'Pending requests';
$string['asv_col_certifications'] = 'Certifications obtained';
$string['asv_certif_globale_courte'] = 'End of A3 global';
$string['asv_aucun_etudiant'] = 'No student to show for this filter.';
$string['asv_synthese_par_acte'] = 'Summary per procedure (number of students)';
$string['asv_attestation_soustitre_global'] = 'End of A3 global certification — delegable veterinary procedures (ASV) of levels A1, A2 and A3';
$string['asv_attestation_texte_global'] = 'has validated, in simulation then on a live animal, all the delegable veterinary procedures of levels A1, A2 and A3 listed below:';

// Parcours étudiant, indisponibilités, démarrage de séance.
$string['parcours_prochaine_echeance'] = 'next deadline:';
$string['parcours_avancement'] = '{$a->realises} required workshop(s) done out of {$a->total} ({$a->pct}%)';
$string['parcours_col_requis'] = 'Required for completion';
$string['parcours_col_echeance'] = 'Deadline';
$string['parcours_en_retard'] = 'overdue';
$string['atelier_non_demarrable'] = 'This workshop is currently unavailable: no session can be started.';
$string['indispo_motif'] = 'Reason for unavailability (visible to students)';
$string['indispo_motif_requis'] = 'Give the reason for the unavailability: it is shown to students.';
$string['indispo_echeance'] = 'Expected back in service';
$string['indispo_historique'] = 'Unavailability history';
$string['indispo_debut'] = 'Start';
$string['indispo_referent'] = 'Contact person';
$string['indispo_cloturee'] = 'Closed';
$string['indispo_en_cours'] = 'Ongoing';
$string['indispo_retour_prevu'] = 'Expected back on {$a}.';
$string['privacy:metadata:local_simhub_asv_valsim:commentaire'] = 'Supervisor remark or reason for cancelling the validation';
$string['setting_categoryid'] = 'SimHub category';
$string['setting_categoryid_desc'] = 'Course category where cross-cutting SimHub roles are assigned (room manager, functional administrator, ASV trainer). The functional administrator assigns these roles there, without an administrator account. Teachers do not need them: their rights come from the SimHub activity of their course unit. Roles already assigned at system level remain valid.';
$string['setting_categoryid_systeme'] = 'None (system level)';
$string['ae_derniere_modification'] = 'Grid shared by every course unit using this workshop. Last change: {$a->auteur}, on {$a->date}.';
$string['event_session_validated'] = 'Workshop session validated or refused';
$string['event_parcours_updated'] = 'Pathway workshops changed';
$string['privacy:metadata:personnel'] = 'References to staff in the school\'s shared framework (workshops, unavailabilities, resources, pathways, grids, ASV acts, session codes). When a user is deleted, records are kept and the reference is removed.';
$string['privacy:metadata:personnel:referentuserid'] = 'Person in charge of the workshop or unavailability.';
$string['privacy:metadata:personnel:usermodified'] = 'Author of the last change.';
$string['privacy:metadata:personnel:createuruserid'] = 'Supervisor who generated the session code.';
$string['champ_categorie'] = 'Category';
$string['filtre_statut'] = 'Availability';
$string['filtre_statut_visibles'] = 'Active and unavailable';
$string['filtre_statut_actif'] = 'Active only';
$string['filtre_statut_indisponible'] = 'Unavailable only';
$string['carte_uc'] = 'Course units:';
$string['session_statut_commence'] = 'Started';
$string['session_statut_realise'] = 'Completed';
$string['session_statut_certifie'] = 'Validated';
$string['session_statut_non_termine'] = 'To redo';
$string['session_val_valide'] = 'Validated by a supervisor';
$string['session_val_refuse'] = 'Refused by a supervisor';
$string['session_demarree_le'] = 'Started on';
$string['session_motif'] = 'To check';
$string['session_motif_nonverifie'] = 'presence not verified';
$string['session_motif_duree'] = 'unusually short ({$a->duree} min for {$a->indicative} min expected)';
$string['setting_reseauxsalle'] = 'Simulation room network';
$string['setting_reseauxsalle_desc'] = 'IP ranges of the room, one per line (e.g. 192.168.10.0/24, 10.2.3.4-50, 172.16.). When the anti-fake-scan control is enabled, a student connected from this network starts the session without a code (§7.3). Empty: no network recognition.';
$string['setting_dureeminpct'] = 'Minimum session length (% of expected duration)';
$string['setting_dureeminpct_desc'] = 'A session finished in less than this percentage of the workshop\'s expected duration is flagged to supervisors (§7.1), without being blocked. For example 30: a 20-minute workshop finished in under 6 minutes is flagged. 0: no flag.';
$string['export_avancement'] = 'Progress (%)';
$string['export_fin'] = 'Finished on';
$string['export_validation'] = 'Validation';
$string['export_format_csv'] = 'CSV';
$string['export_format_xlsx'] = 'Excel (XLSX)';
$string['export_format_ods'] = 'LibreOffice (ODS)';
$string['export_telecharger'] = 'Download:';
$string['export_cohorte'] = 'Cohort tracking';
$string['col_uc'] = 'Course unit';
$string['champ_niveauattendu'] = 'Expected level';
$string['champ_obligatoire'] = 'Mandatory';
$string['champ_echeance'] = 'Due date';
$string['champ_type'] = 'Type';
$string['visibilite_etudiant'] = 'Visible to students';
$string['champ_cohorte_optionnel'] = 'Cohort (optional, to recommend directly to its members)';
$string['stats_titre'] = 'Criteria to work on';
$string['stats_intro'] = 'Student answers to the self-assessment grid, criterion by criterion, most often marked "to redo" or "to consolidate" first (§7.1). Highlighted rows exceed 50 %.';
$string['stats_aucune'] = 'No self-assessment recorded for this workshop.';
$string['stats_reponses'] = 'Answers';
$string['stats_rubrique'] = 'Section';
$string['stats_critere'] = 'Criterion';
$string['stats_lien'] = 'Criteria to work on';
$string['filtre_annee_optionnel'] = 'Study year (optional)';
$string['parcours_uc_verrouille'] = 'This pathway belongs to a course unit SimHub activity: its name, type and course are edited from the activity.';
$string['import_type_ateliers'] = 'Workshop records';
$string['import_type_localisation'] = 'Location (room, zone, station)';
$string['import_type_ressources'] = 'Resource links';
$string['import_type_help'] = 'Workshops: number and name required; a known number is updated. Location: number, then room, zone, station or hint; only the columns present are changed. Resources: number, title and address (URL), with optional type and visibility; a resource with the same title is updated. Links: number, then course unit (course id or short name), year, cohort, mandatory, expected level. Pathways: pathway name, number, order, mandatory (yes/no).';
$string['import_lancer'] = 'Import';
$string['import_format_refuse'] = 'Unrecognised format: use a CSV, XLSX or ODS file.';
$string['import_bilan_crees'] = '{$a} created';
$string['import_bilan_majs'] = '{$a} updated';
$string['import_bilan_parcours'] = '{$a} pathway(s) created';
$string['import_ligne_ressource'] = 'Line {$a}: missing or invalid title or address (URL).';
$string['privacy:metadata:local_simhub_asv_valanimal:emailvalidateur'] = 'The validator\'s email address, to which the validation link was sent.';
$string['asv_email_validateur'] = 'Validator\'s email address';
$string['asv_email_validateur_help'] = 'Professional address of the veterinarian, placement supervisor or authorised trainer who supervised the procedure. The validation link is emailed to them; you do not receive it. This address appears in your logbook.';
$string['asv_email_etudiant_refuse'] = 'Enter the validator\'s address, not your own.';
$string['asv_envoyer_lien'] = 'Send the link to the validator';
$string['asv_envoyer_autre_adresse'] = 'Send to another address (the previous link will stop working)';
$string['asv_renvoyer_lien'] = 'Resend the email';
$string['asv_lien_envoye'] = 'The validation link has been sent to {$a}.';
$string['asv_lien_non_envoye'] = 'The email could not be sent to {$a}. Check the address or contact the administrator.';
$string['asv_demande_envoyee'] = 'Request sent to {$a->email}. The link is valid until {$a->date}.';
$string['asv_deja_valide_animal'] = 'This procedure is already validated on a live animal.';
$string['asv_autovalidation_interdite'] = 'You cannot validate your own procedures. This link is intended for the veterinarian, placement supervisor or trainer who supervised the procedure.';
$string['asv_mail_sujet'] = 'Validation of an ASV procedure on a live animal: {$a->etudiant}';
$string['asv_mail_corps'] = 'Hello,

{$a->etudiant} asks you to validate the following procedure, performed under your supervision on a live animal:

{$a->acte}

To validate it, open this link (no account needed):
{$a->lien}

This link is valid until {$a->expire}. Do not pass it on to the student.
If you did not supervise this procedure, please ignore this message.

{$a->site}';
